### ISSUE TITLE
Alias: -- key null from getKey() call

### ISSUE THREAD

**Issue by simon-inman** [OpenAS2/OpenAs2App#170]
Getting issues sending messages on version 2.10 with error: org.openas2.cert.KeyNotFoundException: Certificate: []
certificate is in the keystore and matches the alias in the partnerships x509_alias.

Inbound messages are fine, just outbound.

---

>2019-11-05 13:54:41.935 FINE DirectoryPollingModule: processing /home/simon/edi_store/as2/mcrcode/outbox/test.2
2019-11-05 13:54:42.177 FINE MessageBuilderModule: File assigned to message: test.2 [<OPENAS2-05112019135441+0000-42273dd1-a0e7-4798-ada7-ee9dec8b7e1c@mcrcode.as2.prd_edihub.online.as2.prd>]
2019-11-05 13:54:42.178 FINE AS2SenderModule: message sender invoked [<OPENAS2-05112019135441+0000-42273dd1-a0e7-4798-ada7-ee9dec8b7e1c@mcrcode.as2.prd_edihub.online.as2.prd>]
2019-11-05 13:54:42.296 ERROR AS2SenderModule: Certificate: [
[
  Version: V3
  Subject: C=None, ST=None, L=None, OU=None, O=None, CN=Simon Inman
  Signature Algorithm: SHA256withRSA, OID = 1.2.840.113549.1.1.11

  Key:  Sun RSA public key, 4096 bits
  modulus: 681828796248977367929906591617239887194163734716679855681949540394842788987835714053100898928158590299117747736354875182080760844904300292280696320438532182923908084002405157630245480438179055509496936106576072026758011775044017634639371728481167899157228055179279274542490941424988315319123605053307511587624291056777592254375160193740696166501206650075714081492944651181813520732227315299784558230318764215615858228931240232702026706990988287172837881622765693323630559046761549912109233948765493687707860900367997168966162150307790732898837342237093954490538820624221276300709402034197834476104614985233706286342200019703541502477018347340826194232781949312024806322582954326499845873605856770232794586291316074749262700336601865357798158620983615396499858406450358024601802914179527230647923229970737868426746815623025769205710681828688690513887086019468867539808305257325287894843387502917599376644660845203503019631027104997395092573411614084236932983130405358892831389285248416605572609638580449422534422729589532872128490280080353098047478167781148152332740716179240753183658191194310964018137600741063615015117416663095564356874482862456403111281146771395454151756091163307331256534476951328411334509797202112810724306926081
  public exponent: 65537
  Validity: [From: Sun Oct 06 10:45:28 UTC 2019,
               To: Fri Nov 02 10:45:28 UTC 2029]
  Issuer: C=None, ST=None, L=None, OU=None, O=None, CN=Simon Inman
  SerialNumber: [    016e3b2b 5dc3]

Certificate Extensions: 4
[1]: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

[2]: ObjectId: 2.5.29.37 Criticality=false
ExtendedKeyUsages [
  serverAuth
  clientAuth
  anyExtendedKeyUsage
]

[3]: ObjectId: 2.5.29.15 Criticality=false
KeyUsage [
  DigitalSignature
  Key_Encipherment
  Data_Encipherment
  Key_CertSign
  Crl_Sign
]

[4]: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: C6 95 6A E4 48 9C CB D9   47 D4 CA B3 0B A9 89 F4  ..j.H...G.......
0010: F4 A3 E4 97                                        ....
]
]

]
  Algorithm: [SHA256withRSA]
  Signature:
0000: 47 A3 CA EE EC 10 68 17   B1 77 B2 C4 14 0B 27 62  G.....h..w....'b
0010: 08 8B E6 32 4D 65 BF 70   4F C8 57 73 AD 67 90 E4  ...2Me.pO.Ws.g..
0020: F2 FF 72 22 1B CE 22 32   41 6D 6E C7 9A D0 96 D7  ..r".."2Amn.....
0030: 17 68 76 28 8A E8 4C 32   96 60 BD F7 5B 2D 4A F0  .hv(..L2.`..[-J.
0040: 2B 09 0C 9A 56 A0 9C 1A   3D 94 56 90 E8 9C AF B1  +...V...=.V.....
0050: 99 8E B4 2E 5A 4B 49 78   AA 72 CB 73 91 77 E3 91  ....ZKIx.r.s.w..
0060: 6C 6A 00 91 DB B8 CB 22   49 CE A2 80 6A 5E 45 52  lj....."I...j^ER
0070: 6E 67 DF F8 C7 77 3E 0D   B1 0F 23 D4 CD 5A 09 10  ng...w>...#..Z..
0080: 99 AE B4 A6 16 63 7C 27   2D 3C 6A 0B E3 A2 A8 F8  .....c.'-<j.....
0090: 24 8C 79 E8 59 BA 46 10   E8 DC 70 37 94 44 92 50  $.y.Y.F...p7.D.P
00A0: 51 C4 61 42 40 B3 7C BA   F6 68 B6 32 EF 47 E6 7F  Q.aB@....h.2.G..
00B0: C5 86 CB D2 10 F7 BE 27   C8 3B 57 53 DB D1 44 28  .......'.;WS..D(
00C0: 34 6B 27 0B 91 08 2D 70   9E C8 A3 C3 E3 A0 7C 7B  4k'...-p........
00D0: 16 4E 45 AE 20 FA 6D 5B   C6 67 90 9F EF C5 CE BC  .NE. .m[.g......
00E0: 82 A8 86 63 A3 6E C9 17   0C 2F 3E B1 FD 51 60 0B  ...c.n.../>..Q`.
00F0: DA A9 BE E0 90 1B C9 A1   2B BD 19 84 BF 41 D7 7D  ........+....A..
0100: 58 8C E6 57 99 E2 97 A4   86 AD 56 AA 30 D0 EC 3A  X..W......V.0..:
0110: 82 9B C1 09 CF 6E FE 4B   CA D0 44 65 8A CA 0A F7  .....n.K..De....
0120: AD 1A 6A 30 72 0A 5B BA   9D 34 53 86 97 8B 33 63  ..j0r.[..4S...3c
0130: 29 DA AA EE AF AB 33 85   33 5C 41 71 AD A1 55 47  ).....3.3\Aq..UG
0140: C7 71 13 E5 25 C9 B8 C5   F4 26 11 D2 71 DF A0 44  .q..%....&..q..D
0150: C7 80 26 08 2F 9B A8 93   0E FD 4E CA 48 5B B3 95  ..&./.....N.H[..
0160: 3D F5 AA 70 6A F8 7C 4B   6B 93 D1 F3 5F 41 0C ED  =..pj..Kk..._A..
0170: 35 DF 2A 8E 39 B5 D1 A7   F5 22 38 F5 2B C2 9D CD  5.*.9...."8.+...
0180: BC 0E C5 46 37 39 30 E5   67 50 80 26 5F D3 FB A3  ...F790.gP.&_...
0190: 40 58 0B 2E EE 93 2A 66   D3 86 77 06 A7 5B 49 3F  @X....*f..w..[I?
01A0: C6 44 17 20 AA 77 08 25   4F 31 D0 B3 76 E0 4D 14  .D. .w.%O1..v.M.
01B0: 4A 68 9E D6 6F 6D CE 40   4E 22 2E 2A 85 2C 83 FA  Jh..om.@N".*.,..
01C0: D0 6A 50 BA 71 36 73 6E   31 43 FC 61 21 82 9B 8A  .jP.q6sn1C.a!...
01D0: F6 65 46 9E 36 5E 28 5B   47 39 B8 39 8B B0 15 D6  .eF.6^([G9.9....
01E0: 02 D0 83 08 85 41 19 41   68 20 C3 E7 52 BD 7E ED  .....A.Ah ..R...
01F0: 37 06 F3 A3 57 57 24 01   02 3A E6 1C B2 9F 00 40  7...WW$..:.....@

], Alias: -- key null from getKey(mcrcode) call [<OPENAS2-05112019135441+0000-42273dd1-a0e7-4798-ada7-ee9dec8b7e1c@mcrcode.as2.prd_edihub.online.as2.prd>]
org.openas2.cert.KeyNotFoundException: Certificate: [
[
  Version: V3
  Subject: C=None, ST=None, L=None, OU=None, O=None, CN=Simon Inman
  Signature Algorithm: SHA256withRSA, OID = 1.2.840.113549.1.1.11

  Key:  Sun RSA public key, 4096 bits
  modulus: 681828796248977367929906591617239887194163734716679855681949540394842788987835714053100898928158590299117747736354875182080760844904300292280696320438532182923908084002405157630245480438179055509496936106576072026758011775044017634639371728481167899157228055179279274542490941424988315319123605053307511587624291056777592254375160193740696166501206650075714081492944651181813520732227315299784558230318764215615858228931240232702026706990988287172837881622765693323630559046761549912109233948765493687707860900367997168966162150307790732898837342237093954490538820624221276300709402034197834476104614985233706286342200019703541502477018347340826194232781949312024806322582954326499845873605856770232794586291316074749262700336601865357798158620983615396499858406450358024601802914179527230647923229970737868426746815623025769205710681828688690513887086019468867539808305257325287894843387502917599376644660845203503019631027104997395092573411614084236932983130405358892831389285248416605572609638580449422534422729589532872128490280080353098047478167781148152332740716179240753183658191194310964018137600741063615015117416663095564356874482862456403111281146771395454151756091163307331256534476951328411334509797202112810724306926081
  public exponent: 65537
  Validity: [From: Sun Oct 06 10:45:28 UTC 2019,
               To: Fri Nov 02 10:45:28 UTC 2029]
  Issuer: C=None, ST=None, L=None, OU=None, O=None, CN=Simon Inman
  SerialNumber: [    016e3b2b 5dc3]

Certificate Extensions: 4
[1]: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

[2]: ObjectId: 2.5.29.37 Criticality=false
ExtendedKeyUsages [
  serverAuth
  clientAuth
  anyExtendedKeyUsage
]

[3]: ObjectId: 2.5.29.15 Criticality=false
KeyUsage [
  DigitalSignature
  Key_Encipherment
  Data_Encipherment
  Key_CertSign
  Crl_Sign
]

[4]: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: C6 95 6A E4 48 9C CB D9   47 D4 CA B3 0B A9 89 F4  ..j.H...G.......
0010: F4 A3 E4 97                                        ....
]
]

]
  Algorithm: [SHA256withRSA]
  Signature:
0000: 47 A3 CA EE EC 10 68 17   B1 77 B2 C4 14 0B 27 62  G.....h..w....'b
0010: 08 8B E6 32 4D 65 BF 70   4F C8 57 73 AD 67 90 E4  ...2Me.pO.Ws.g..
0020: F2 FF 72 22 1B CE 22 32   41 6D 6E C7 9A D0 96 D7  ..r".."2Amn.....
0030: 17 68 76 28 8A E8 4C 32   96 60 BD F7 5B 2D 4A F0  .hv(..L2.`..[-J.
0040: 2B 09 0C 9A 56 A0 9C 1A   3D 94 56 90 E8 9C AF B1  +...V...=.V.....
0050: 99 8E B4 2E 5A 4B 49 78   AA 72 CB 73 91 77 E3 91  ....ZKIx.r.s.w..
0060: 6C 6A 00 91 DB B8 CB 22   49 CE A2 80 6A 5E 45 52  lj....."I...j^ER
0070: 6E 67 DF F8 C7 77 3E 0D   B1 0F 23 D4 CD 5A 09 10  ng...w>...#..Z..
0080: 99 AE B4 A6 16 63 7C 27   2D 3C 6A 0B E3 A2 A8 F8  .....c.'-<j.....
0090: 24 8C 79 E8 59 BA 46 10   E8 DC 70 37 94 44 92 50  $.y.Y.F...p7.D.P
00A0: 51 C4 61 42 40 B3 7C BA   F6 68 B6 32 EF 47 E6 7F  Q.aB@....h.2.G..
00B0: C5 86 CB D2 10 F7 BE 27   C8 3B 57 53 DB D1 44 28  .......'.;WS..D(
00C0: 34 6B 27 0B 91 08 2D 70   9E C8 A3 C3 E3 A0 7C 7B  4k'...-p........
00D0: 16 4E 45 AE 20 FA 6D 5B   C6 67 90 9F EF C5 CE BC  .NE. .m[.g......
00E0: 82 A8 86 63 A3 6E C9 17   0C 2F 3E B1 FD 51 60 0B  ...c.n.../>..Q`.
00F0: DA A9 BE E0 90 1B C9 A1   2B BD 19 84 BF 41 D7 7D  ........+....A..
0100: 58 8C E6 57 99 E2 97 A4   86 AD 56 AA 30 D0 EC 3A  X..W......V.0..:
0110: 82 9B C1 09 CF 6E FE 4B   CA D0 44 65 8A CA 0A F7  .....n.K..De....
0120: AD 1A 6A 30 72 0A 5B BA   9D 34 53 86 97 8B 33 63  ..j0r.[..4S...3c
0130: 29 DA AA EE AF AB 33 85   33 5C 41 71 AD A1 55 47  ).....3.3\Aq..UG
0140: C7 71 13 E5 25 C9 B8 C5   F4 26 11 D2 71 DF A0 44  .q..%....&..q..D
0150: C7 80 26 08 2F 9B A8 93   0E FD 4E CA 48 5B B3 95  ..&./.....N.H[..
0160: 3D F5 AA 70 6A F8 7C 4B   6B 93 D1 F3 5F 41 0C ED  =..pj..Kk..._A..
0170: 35 DF 2A 8E 39 B5 D1 A7   F5 22 38 F5 2B C2 9D CD  5.*.9...."8.+...
0180: BC 0E C5 46 37 39 30 E5   67 50 80 26 5F D3 FB A3  ...F790.gP.&_...
0190: 40 58 0B 2E EE 93 2A 66   D3 86 77 06 A7 5B 49 3F  @X....*f..w..[I?
01A0: C6 44 17 20 AA 77 08 25   4F 31 D0 B3 76 E0 4D 14  .D. .w.%O1..v.M.
01B0: 4A 68 9E D6 6F 6D CE 40   4E 22 2E 2A 85 2C 83 FA  Jh..om.@N".*.,..
01C0: D0 6A 50 BA 71 36 73 6E   31 43 FC 61 21 82 9B 8A  .jP.q6sn1C.a!...
01D0: F6 65 46 9E 36 5E 28 5B   47 39 B8 39 8B B0 15 D6  .eF.6^([G9.9....
01E0: 02 D0 83 08 85 41 19 41   68 20 C3 E7 52 BD 7E ED  .....A.Ah ..R...
01F0: 37 06 F3 A3 57 57 24 01   02 3A E6 1C B2 9F 00 40  7...WW$..:.....@

], Alias: -- key null from getKey(mcrcode) call
        at org.openas2.cert.PKCS12CertificateFactory.getPrivateKey(PKCS12CertificateFactory.java:187)
        at org.openas2.cert.PKCS12CertificateFactory.getPrivateKey(PKCS12CertificateFactory.java:199)
        at org.openas2.processor.sender.AS2SenderModule.secure(AS2SenderModule.java:350)
        at org.openas2.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:89)
        at org.openas2.processor.DefaultProcessor.handle(DefaultProcessor.java:65)
        at org.openas2.processor.receiver.MessageBuilderModule.processDocument(MessageBuilderModule.java:182)
        at org.openas2.processor.receiver.DirectoryPollingModule.processFile(DirectoryPollingModule.java:196)
        at org.openas2.processor.receiver.DirectoryPollingModule.updateTracking(DirectoryPollingModule.java:170)
        at org.openas2.processor.receiver.DirectoryPollingModule.poll(DirectoryPollingModule.java:81)
        at org.openas2.processor.receiver.PollingModule$PollTask.run(PollingModule.java:62)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

2019-11-05 13:54:42.492 ERROR OpenAS2Exception: Error occurred:: null
    Sources: {}
org.openas2.processor.ProcessorException: null
        at org.openas2.processor.DefaultProcessor.handle(DefaultProcessor.java:70)
        at org.openas2.processor.receiver.MessageBuilderModule.processDocument(MessageBuilderModule.java:182)
        at org.openas2.processor.receiver.DirectoryPollingModule.processFile(DirectoryPollingModule.java:196)
        at org.openas2.processor.receiver.DirectoryPollingModule.updateTracking(DirectoryPollingModule.java:170)
        at org.openas2.processor.receiver.DirectoryPollingModule.poll(DirectoryPollingModule.java:81)
        at org.openas2.processor.receiver.PollingModule$PollTask.run(PollingModule.java:62)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

2019-11-05 13:54:42.493 ERROR MessageBuilderModule: Fatal error sending message: null
org.openas2.OpenAS2Exception: Error setting up message for sending.
        at org.openas2.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:101)
        at org.openas2.processor.DefaultProcessor.handle(DefaultProcessor.java:65)
        at org.openas2.processor.receiver.MessageBuilderModule.processDocument(MessageBuilderModule.java:182)
        at org.openas2.processor.receiver.DirectoryPollingModule.processFile(DirectoryPollingModule.java:196)
        at org.openas2.processor.receiver.DirectoryPollingModule.updateTracking(DirectoryPollingModule.java:170)
        at org.openas2.processor.receiver.DirectoryPollingModule.poll(DirectoryPollingModule.java:81)
        at org.openas2.processor.receiver.PollingModule$PollTask.run(PollingModule.java:62)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: org.openas2.cert.KeyNotFoundException: Certificate: [
[
  Version: V3
  Subject: C=None, ST=None, L=None, OU=None, O=None, CN=Simon Inman
  Signature Algorithm: SHA256withRSA, OID = 1.2.840.113549.1.1.11

  Key:  Sun RSA public key, 4096 bits
  modulus: 681828796248977367929906591617239887194163734716679855681949540394842788987835714053100898928158590299117747736354875182080760844904300292280696320438532182923908084002405157630245480438179055509496936106576072026758011775044017634639371728481167899157228055179279274542490941424988315319123605053307511587624291056777592254375160193740696166501206650075714081492944651181813520732227315299784558230318764215615858228931240232702026706990988287172837881622765693323630559046761549912109233948765493687707860900367997168966162150307790732898837342237093954490538820624221276300709402034197834476104614985233706286342200019703541502477018347340826194232781949312024806322582954326499845873605856770232794586291316074749262700336601865357798158620983615396499858406450358024601802914179527230647923229970737868426746815623025769205710681828688690513887086019468867539808305257325287894843387502917599376644660845203503019631027104997395092573411614084236932983130405358892831389285248416605572609638580449422534422729589532872128490280080353098047478167781148152332740716179240753183658191194310964018137600741063615015117416663095564356874482862456403111281146771395454151756091163307331256534476951328411334509797202112810724306926081
  public exponent: 65537
  Validity: [From: Sun Oct 06 10:45:28 UTC 2019,
               To: Fri Nov 02 10:45:28 UTC 2029]
  Issuer: C=None, ST=None, L=None, OU=None, O=None, CN=Simon Inman
  SerialNumber: [    016e3b2b 5dc3]

Certificate Extensions: 4
[1]: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

[2]: ObjectId: 2.5.29.37 Criticality=false
ExtendedKeyUsages [
  serverAuth
  clientAuth
  anyExtendedKeyUsage
]

[3]: ObjectId: 2.5.29.15 Criticality=false
KeyUsage [
  DigitalSignature
  Key_Encipherment
  Data_Encipherment
  Key_CertSign
  Crl_Sign
]

[4]: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: C6 95 6A E4 48 9C CB D9   47 D4 CA B3 0B A9 89 F4  ..j.H...G.......
0010: F4 A3 E4 97                                        ....
]
]

]
  Algorithm: [SHA256withRSA]
  Signature:
0000: 47 A3 CA EE EC 10 68 17   B1 77 B2 C4 14 0B 27 62  G.....h..w....'b
0010: 08 8B E6 32 4D 65 BF 70   4F C8 57 73 AD 67 90 E4  ...2Me.pO.Ws.g..
0020: F2 FF 72 22 1B CE 22 32   41 6D 6E C7 9A D0 96 D7  ..r".."2Amn.....
0030: 17 68 76 28 8A E8 4C 32   96 60 BD F7 5B 2D 4A F0  .hv(..L2.`..[-J.
0040: 2B 09 0C 9A 56 A0 9C 1A   3D 94 56 90 E8 9C AF B1  +...V...=.V.....
0050: 99 8E B4 2E 5A 4B 49 78   AA 72 CB 73 91 77 E3 91  ....ZKIx.r.s.w..
0060: 6C 6A 00 91 DB B8 CB 22   49 CE A2 80 6A 5E 45 52  lj....."I...j^ER
0070: 6E 67 DF F8 C7 77 3E 0D   B1 0F 23 D4 CD 5A 09 10  ng...w>...#..Z..
0080: 99 AE B4 A6 16 63 7C 27   2D 3C 6A 0B E3 A2 A8 F8  .....c.'-<j.....
0090: 24 8C 79 E8 59 BA 46 10   E8 DC 70 37 94 44 92 50  $.y.Y.F...p7.D.P
00A0: 51 C4 61 42 40 B3 7C BA   F6 68 B6 32 EF 47 E6 7F  Q.aB@....h.2.G..
00B0: C5 86 CB D2 10 F7 BE 27   C8 3B 57 53 DB D1 44 28  .......'.;WS..D(
00C0: 34 6B 27 0B 91 08 2D 70   9E C8 A3 C3 E3 A0 7C 7B  4k'...-p........
00D0: 16 4E 45 AE 20 FA 6D 5B   C6 67 90 9F EF C5 CE BC  .NE. .m[.g......
00E0: 82 A8 86 63 A3 6E C9 17   0C 2F 3E B1 FD 51 60 0B  ...c.n.../>..Q`.
00F0: DA A9 BE E0 90 1B C9 A1   2B BD 19 84 BF 41 D7 7D  ........+....A..
0100: 58 8C E6 57 99 E2 97 A4   86 AD 56 AA 30 D0 EC 3A  X..W......V.0..:
0110: 82 9B C1 09 CF 6E FE 4B   CA D0 44 65 8A CA 0A F7  .....n.K..De....
0120: AD 1A 6A 30 72 0A 5B BA   9D 34 53 86 97 8B 33 63  ..j0r.[..4S...3c
0130: 29 DA AA EE AF AB 33 85   33 5C 41 71 AD A1 55 47  ).....3.3\Aq..UG
0140: C7 71 13 E5 25 C9 B8 C5   F4 26 11 D2 71 DF A0 44  .q..%....&..q..D
0150: C7 80 26 08 2F 9B A8 93   0E FD 4E CA 48 5B B3 95  ..&./.....N.H[..
0160: 3D F5 AA 70 6A F8 7C 4B   6B 93 D1 F3 5F 41 0C ED  =..pj..Kk..._A..
0170: 35 DF 2A 8E 39 B5 D1 A7   F5 22 38 F5 2B C2 9D CD  5.*.9...."8.+...
0180: BC 0E C5 46 37 39 30 E5   67 50 80 26 5F D3 FB A3  ...F790.gP.&_...
0190: 40 58 0B 2E EE 93 2A 66   D3 86 77 06 A7 5B 49 3F  @X....*f..w..[I?
01A0: C6 44 17 20 AA 77 08 25   4F 31 D0 B3 76 E0 4D 14  .D. .w.%O1..v.M.
01B0: 4A 68 9E D6 6F 6D CE 40   4E 22 2E 2A 85 2C 83 FA  Jh..om.@N".*.,..
01C0: D0 6A 50 BA 71 36 73 6E   31 43 FC 61 21 82 9B 8A  .jP.q6sn1C.a!...
01D0: F6 65 46 9E 36 5E 28 5B   47 39 B8 39 8B B0 15 D6  .eF.6^([G9.9....
01E0: 02 D0 83 08 85 41 19 41   68 20 C3 E7 52 BD 7E ED  .....A.Ah ..R...
01F0: 37 06 F3 A3 57 57 24 01   02 3A E6 1C B2 9F 00 40  7...WW$..:.....@

], Alias: -- key null from getKey(mcrcode) call
        at org.openas2.cert.PKCS12CertificateFactory.getPrivateKey(PKCS12CertificateFactory.java:187)
        at org.openas2.cert.PKCS12CertificateFactory.getPrivateKey(PKCS12CertificateFactory.java:199)
        at org.openas2.processor.sender.AS2SenderModule.secure(AS2SenderModule.java:350)
        at org.openas2.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:89)
        ... 8 more
 [<OPENAS2-05112019135441+0000-42273dd1-a0e7-4798-ada7-ee9dec8b7e1c@mcrcode.as2.prd_edihub.online.as2.prd>]
org.openas2.processor.ProcessorException: null
org.openas2.OpenAS2Exception: Error setting up message for sending.
        at org.openas2.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:101)
        at org.openas2.processor.DefaultProcessor.handle(DefaultProcessor.java:65)
        at org.openas2.processor.receiver.MessageBuilderModule.processDocument(MessageBuilderModule.java:182)
        at org.openas2.processor.receiver.DirectoryPollingModule.processFile(DirectoryPollingModule.java:196)
        at org.openas2.processor.receiver.DirectoryPollingModule.updateTracking(DirectoryPollingModule.java:170)
        at org.openas2.processor.receiver.DirectoryPollingModule.poll(DirectoryPollingModule.java:81)
        at org.openas2.processor.receiver.PollingModule$PollTask.run(PollingModule.java:62)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: org.openas2.cert.KeyNotFoundException: Certificate: [
[
  Version: V3
  Subject: C=None, ST=None, L=None, OU=None, O=None, CN=Simon Inman
  Signature Algorithm: SHA256withRSA, OID = 1.2.840.113549.1.1.11

  Key:  Sun RSA public key, 4096 bits
  modulus: 681828796248977367929906591617239887194163734716679855681949540394842788987835714053100898928158590299117747736354875182080760844904300292280696320438532182923908084002405157630245480438179055509496936106576072026758011775044017634639371728481167899157228055179279274542490941424988315319123605053307511587624291056777592254375160193740696166501206650075714081492944651181813520732227315299784558230318764215615858228931240232702026706990988287172837881622765693323630559046761549912109233948765493687707860900367997168966162150307790732898837342237093954490538820624221276300709402034197834476104614985233706286342200019703541502477018347340826194232781949312024806322582954326499845873605856770232794586291316074749262700336601865357798158620983615396499858406450358024601802914179527230647923229970737868426746815623025769205710681828688690513887086019468867539808305257325287894843387502917599376644660845203503019631027104997395092573411614084236932983130405358892831389285248416605572609638580449422534422729589532872128490280080353098047478167781148152332740716179240753183658191194310964018137600741063615015117416663095564356874482862456403111281146771395454151756091163307331256534476951328411334509797202112810724306926081
  public exponent: 65537
  Validity: [From: Sun Oct 06 10:45:28 UTC 2019,
               To: Fri Nov 02 10:45:28 UTC 2029]
  Issuer: C=None, ST=None, L=None, OU=None, O=None, CN=Simon Inman
  SerialNumber: [    016e3b2b 5dc3]

Certificate Extensions: 4
[1]: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

[2]: ObjectId: 2.5.29.37 Criticality=false
ExtendedKeyUsages [
  serverAuth
  clientAuth
  anyExtendedKeyUsage
]

[3]: ObjectId: 2.5.29.15 Criticality=false
KeyUsage [
  DigitalSignature
  Key_Encipherment
  Data_Encipherment
  Key_CertSign
  Crl_Sign
]

[4]: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: C6 95 6A E4 48 9C CB D9   47 D4 CA B3 0B A9 89 F4  ..j.H...G.......
0010: F4 A3 E4 97                                        ....
]
]

]
  Algorithm: [SHA256withRSA]
  Signature:
0000: 47 A3 CA EE EC 10 68 17   B1 77 B2 C4 14 0B 27 62  G.....h..w....'b
0010: 08 8B E6 32 4D 65 BF 70   4F C8 57 73 AD 67 90 E4  ...2Me.pO.Ws.g..
0020: F2 FF 72 22 1B CE 22 32   41 6D 6E C7 9A D0 96 D7  ..r".."2Amn.....
0030: 17 68 76 28 8A E8 4C 32   96 60 BD F7 5B 2D 4A F0  .hv(..L2.`..[-J.
0040: 2B 09 0C 9A 56 A0 9C 1A   3D 94 56 90 E8 9C AF B1  +...V...=.V.....
0050: 99 8E B4 2E 5A 4B 49 78   AA 72 CB 73 91 77 E3 91  ....ZKIx.r.s.w..
0060: 6C 6A 00 91 DB B8 CB 22   49 CE A2 80 6A 5E 45 52  lj....."I...j^ER
0070: 6E 67 DF F8 C7 77 3E 0D   B1 0F 23 D4 CD 5A 09 10  ng...w>...#..Z..
0080: 99 AE B4 A6 16 63 7C 27   2D 3C 6A 0B E3 A2 A8 F8  .....c.'-<j.....
0090: 24 8C 79 E8 59 BA 46 10   E8 DC 70 37 94 44 92 50  $.y.Y.F...p7.D.P
00A0: 51 C4 61 42 40 B3 7C BA   F6 68 B6 32 EF 47 E6 7F  Q.aB@....h.2.G..
00B0: C5 86 CB D2 10 F7 BE 27   C8 3B 57 53 DB D1 44 28  .......'.;WS..D(
00C0: 34 6B 27 0B 91 08 2D 70   9E C8 A3 C3 E3 A0 7C 7B  4k'...-p........
00D0: 16 4E 45 AE 20 FA 6D 5B   C6 67 90 9F EF C5 CE BC  .NE. .m[.g......
00E0: 82 A8 86 63 A3 6E C9 17   0C 2F 3E B1 FD 51 60 0B  ...c.n.../>..Q`.
00F0: DA A9 BE E0 90 1B C9 A1   2B BD 19 84 BF 41 D7 7D  ........+....A..
0100: 58 8C E6 57 99 E2 97 A4   86 AD 56 AA 30 D0 EC 3A  X..W......V.0..:
0110: 82 9B C1 09 CF 6E FE 4B   CA D0 44 65 8A CA 0A F7  .....n.K..De....
0120: AD 1A 6A 30 72 0A 5B BA   9D 34 53 86 97 8B 33 63  ..j0r.[..4S...3c
0130: 29 DA AA EE AF AB 33 85   33 5C 41 71 AD A1 55 47  ).....3.3\Aq..UG
0140: C7 71 13 E5 25 C9 B8 C5   F4 26 11 D2 71 DF A0 44  .q..%....&..q..D
0150: C7 80 26 08 2F 9B A8 93   0E FD 4E CA 48 5B B3 95  ..&./.....N.H[..
0160: 3D F5 AA 70 6A F8 7C 4B   6B 93 D1 F3 5F 41 0C ED  =..pj..Kk..._A..
0170: 35 DF 2A 8E 39 B5 D1 A7   F5 22 38 F5 2B C2 9D CD  5.*.9...."8.+...
0180: BC 0E C5 46 37 39 30 E5   67 50 80 26 5F D3 FB A3  ...F790.gP.&_...
0190: 40 58 0B 2E EE 93 2A 66   D3 86 77 06 A7 5B 49 3F  @X....*f..w..[I?
01A0: C6 44 17 20 AA 77 08 25   4F 31 D0 B3 76 E0 4D 14  .D. .w.%O1..v.M.
01B0: 4A 68 9E D6 6F 6D CE 40   4E 22 2E 2A 85 2C 83 FA  Jh..om.@N".*.,..
01C0: D0 6A 50 BA 71 36 73 6E   31 43 FC 61 21 82 9B 8A  .jP.q6sn1C.a!...
01D0: F6 65 46 9E 36 5E 28 5B   47 39 B8 39 8B B0 15 D6  .eF.6^([G9.9....
01E0: 02 D0 83 08 85 41 19 41   68 20 C3 E7 52 BD 7E ED  .....A.Ah ..R...
01F0: 37 06 F3 A3 57 57 24 01   02 3A E6 1C B2 9F 00 40  7...WW$..:.....@

], Alias: -- key null from getKey(mcrcode) call
        at org.openas2.cert.PKCS12CertificateFactory.getPrivateKey(PKCS12CertificateFactory.java:187)
        at org.openas2.cert.PKCS12CertificateFactory.getPrivateKey(PKCS12CertificateFactory.java:199)
        at org.openas2.processor.sender.AS2SenderModule.secure(AS2SenderModule.java:350)
        at org.openas2.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:89)
        ... 8 more

        at org.openas2.processor.DefaultProcessor.handle(DefaultProcessor.java:70)
        at org.openas2.processor.receiver.MessageBuilderModule.processDocument(MessageBuilderModule.java:182)
        at org.openas2.processor.receiver.DirectoryPollingModule.processFile(DirectoryPollingModule.java:196)
        at org.openas2.processor.receiver.DirectoryPollingModule.updateTracking(DirectoryPollingModule.java:170)
        at org.openas2.processor.receiver.DirectoryPollingModule.poll(DirectoryPollingModule.java:81)
        at org.openas2.processor.receiver.PollingModule$PollTask.run(PollingModule.java:62)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

2019-11-05 13:54:42.513 FINE AS2Util: moved /home/simon/OpenAS2/bin/../config/../data/pendingMDN3/OPENAS2-05112019135441+0000-42273dd1-a0e7-4798-ada7-ee9dec8b7e1c@mcrcode.as2.prd_edihub.online.as2.prd to /home/simon/edi_store/as2/mcrcode/outbox/error/OPENAS2-05112019135441+0000-42273dd1-a0e7-4798-ada7-ee9dec8b7e1c@mcrcode.as2.prd_edihub.online.as2.prd [<OPENAS2-05112019135441+0000-42273dd1-a0e7-4798-ada7-ee9dec8b7e1c@mcrcode.as2.prd_edihub.online.as2.prd>]

**Comment by igwtech** [comment]
Hi, 
   According to our logs seems OpenAS2 cannot find the corresponding private key to encrypt the outgoing message. Have you loaded your PrivateKey in your KeyStore along side with your certificate?
Make sure the password used to encrypt the private key inside your KeyStore matches the one configured in config.xml.

**Comment by uhurusurfa** [comment]
No response
