### ISSUE TITLE
Bump h2 from 1.4.200 to 2.1.210 (#251, #256)

### ISSUE THREAD

**Issue by DushyantTa** [OpenAS2/OpenAs2App#262]
**Issue:** "The write format 1 is smaller than the supported format 2 [2.1.210/5]"

**Stack trace:** 
```
org.h2.jdbc.JdbcSQLNonTransientException: General error: "The write format 1 is smaller than the supported format 2 [2.1.210/5]" [50000-210]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
        at org.h2.message.DbException.get(DbException.java:216)
        at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:166)
        at org.h2.mvstore.db.Store.<init>(Store.java:140)
        at org.h2.engine.Database.<init>(Database.java:324)
        at org.h2.engine.Engine.openSession(Engine.java:92)
        at org.h2.engine.Engine.openSession(Engine.java:222)
        at org.h2.engine.Engine.createSession(Engine.java:201)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
        at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:322)
        at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:352)        at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:233)
        at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:198)
        at org.openas2.processor.msgtracking.EmbeddedDBHandler.getConnection(EmbeddedDBHandler.java:86)
        at org.openas2.processor.msgtracking.DbTrackingModule.persist(DbTrackingModule.java:101)
        at org.openas2.processor.msgtracking.BaseMsgTrackingModule.handle(BaseMsgTrackingModule.java:21)
        at org.openas2.processor.DefaultProcessor.handle(DefaultProcessor.java:55)
        at org.openas2.message.BaseMessage.trackMsgState(BaseMessage.java:424)
        at org.openas2.processor.sender.AS2SenderModule.processResponse(AS2SenderModule.java:218)
        at org.openas2.processor.sender.AS2SenderModule.sendMessage(AS2SenderModule.java:188)
        at org.openas2.processor.sender.AS2SenderModule.handle(AS2SenderModule.java:119)
        at org.openas2.processor.DefaultProcessor.handle(DefaultProcessor.java:55)
        at org.openas2.processor.receiver.MessageBuilderModule.processDocument(MessageBuilderModule.java:179)
        at org.openas2.processor.receiver.DirectoryPollingModule.processFile(DirectoryPollingModule.java:225)
        at org.openas2.processor.receiver.DirectoryPollingModule.updateTracking(DirectoryPollingModule.java:198)
        at org.openas2.processor.receiver.DirectoryPollingModule.poll(DirectoryPollingModule.java:83)
        at org.openas2.processor.receiver.PollingModule$PollTask.run(PollingModule.java:52)
        at java.base/java.util.TimerThread.mainLoop(Unknown Source)
        at java.base/java.util.TimerThread.run(Unknown Source)
Caused by: org.h2.mvstore.MVStoreException: The write format 1 is smaller than the supported format 2 [2.1.210/5]
        at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
        at org.h2.mvstore.MVStore.getUnsupportedWriteFormatException(MVStore.java:1059)
        at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:878)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:455)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4056)
        at org.h2.mvstore.db.Store.<init>(Store.java:129)
        ... 26 more
```
   
       
**Note:** 
- It works as expected, once the h2 dependency version is Restored from 2.1.210 to 1.4.200.
- Validated the inserted row record using h2 Tool Shell. (java -cp h2-1.4.200.jar org.h2.tools.Shell)
- Please share migration steps

**Comment by DushyantTa** [comment]
Persistent databases created by H2 1.4.200 and older versions require export into SQL script with that old version and creation of a new database with the new version and execution of this script in it.
