### ISSUE TITLE
OpenAS2 cannot be under NT_AUTHORITY\Network Service on Windows or with $ in password property

### ISSUE THREAD

**Issue by MilanDadok** [OpenAS2/OpenAs2App#298]
OpensAS2-3.3.0

The service ends immediately
2022-09-08 17:25:45 Apache Commons Daemon procrun stderr initialized.
org.openas2.params.InvalidParameterException: Invalid key (missing closing '$') parsing this string: AP10$
	at org.openas2.params.ParameterParser.format(ParameterParser.java:150)
	at org.openas2.params.ParameterParser.parse(ParameterParser.java:118)
	at org.openas2.XMLSession.loadProperties(XMLSession.java:197)
	at org.openas2.XMLSession.load(XMLSession.java:107)
	at org.openas2.XMLSession.<init>(XMLSession.java:75)
	at org.openas2.app.OpenAS2Server$Builder.run(OpenAS2Server.java:182)
	at org.openas2.app.OpenAS2WindowsService.start(OpenAS2WindowsService.java:30)

It's due to java system properties can have $ in it's value - here it's user.name == windows AD Computer name account
(TRACE stdout)
2022-09-08 17:25:46.468 FINER XMLSession: Parsing property: msg_tracking.db_pwd : OpenAS2
2022-09-08 17:25:46.468 FINER XMLSession: Parsing property: user.script : 
2022-09-08 17:25:46.468 FINER XMLSession: Parsing property: sun.management.compiler : HotSpot 64-Bit Tiered Compilers
2022-09-08 17:25:46.468 FINER XMLSession: Parsing property: java.runtime.version : 17.0.4.1+1-LTS
2022-09-08 17:25:46.468 FINER XMLSession: Parsing property: user.name : AP10$

Same error with $ character in password in config.xml properties, for example
               email.smtppwd="mySmtp$Pwd"

2022-09-08 17:32:03.701 FINER XMLSession: Parsing property: socket.logger.enabled : false
2022-09-08 17:32:03.701 FINER XMLSession: Parsing property: user.country : CZ
2022-09-08 17:32:03.701 FINER XMLSession: Parsing property: email.smtppwd : mySmtp$Pwd

temporary solution for first bug - add to java options 
-Duser.name=NETWORK

The error is in XMLSession.java loadProperties - event password values are reevalueted after comment
        /* Process all loaded values in case they reference other properties in the value
           Use the properties object instead of Properties so we only parse the properties that were in the config.xml
           so that we can use system property values to replace config.xml properties.
         */

**Comment by uhurusurfa** [comment]
For actual $ characters in properties, they must be escaped by a $ character: $$
I will add this to the documentation.

**Comment by uhurusurfa** [comment]
@MilanDadok  Re-reading your original post I think you are pointing out the problem of system properties. I will add code to bypass parsing any properties that are not in config.xml and take the value verbatim.

**Comment by uhurusurfa** [comment]
Fixed in 3.4.0 release.
