### ISSUE TITLE
On Ubuntu 20.04.6 LTS with jdk1.8.0_92 Server not starting.

### ISSUE THREAD

**Issue by epositiveDevang** [OpenAS2/OpenAs2App#377]
**Operating System:**

# uname -a
Linux 5.4.0-172-generic #190-Ubuntu SMP Fri Feb 2 23:24:22 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**#lsb_release -a**

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

**Environment:** 

# env | grep -i java
JAVA_HOME=/opt/jdk1.8.0_92
CLASSPATH=.:..:/opt/jdk1.8.0_92/activation.jar:/opt/jdk1.8.0_92/commons-net-3.2.jar:/opt/jdk1.8.0_92/itextpdf-5.5.0.jar:/opt/jdk1.8.0_92/mail.jar:/opt/jdk1.8.0_92/mq.jar:/opt/jdk1.8.0_92/mysql.jar:/opt/jdk1.8.0_92/opencsv-3.0.jar:/opt/jdk1.8.0_92/jre/lib/rt.jar:/opt/jdk1.8.0_92/src.zip:/opt/jdk1.8.0_92/mysql-connector-java-5.1.10-bin.jar:/opt/jdk1.8.0_92/commons-codec-1.13.jar:/opt/jdk1.8.0_92/google-http-client-1.32.1.jar:/opt/jdk1.8.0_92/google-http-client-jackson2-1.32.1.jar:/opt/jdk1.8.0_92/jackson-databind-2.9.9.3.jar:/opt/jdk1.8.0_92/jackson-core-2.9.9.jar:/opt/jdk1.8.0_92/jackson-annotations-2.9.9.jar:/opt/jdk1.8.0_92/guava-28.1-jre.jar:/opt/jdk1.8.0_92/opencensus-api-0.24.0.jar:/opt/jdk1.8.0_92/opencensus-impl-0.24.0.jar:/opt/jdk1.8.0_92/opencensus-api-0.24.0.jar:/opt/jdk1.8.0_92/opencensus-contrib-http-util-0.24.0.jar:/opt/jdk1.8.0_92/opencensus-impl-core-0.24.0.jar:/opt/jdk1.8.0_92/disruptor-3.4.2.jar:/opt/jdk1.8.0_92/grpc-context-1.24.0.jar:/opt/jdk1.8.0_92/jsch-0.1.42.jar

**Ending with an Error:**

#bin/start-openas2.sh

Running /opt/jdk1.8.0_92/bin/java -Xms32m -Xmx384m -Dorg.apache.commons.logging.Log=org.openas2.logging.Log -Dopenas2.config.file=/opt/openas2/bin/../config/config.xml -cp .:/opt/openas2/bin/../lib/activation-1.1.jar:/opt/openas2/bin/../lib/angus-activation-2.0.2.jar:/opt/openas2/bin/../lib/aopalliance-repackaged-4.0.0-M1.jar:/opt/openas2/bin/../lib/bcmail-jdk18on-1.78.1.jar:/opt/openas2/bin/../lib/bcpg-jdk18on-1.78.1.jar:/opt/openas2/bin/../lib/bcpkix-jdk18on-1.78.1.jar:/opt/openas2/bin/../lib/bcprov-jdk18on-1.78.1.jar:/opt/openas2/bin/../lib/bcutil-jdk18on-1.78.1.jar:/opt/openas2/bin/../lib/commons-cli-1.7.0.jar:/opt/openas2/bin/../lib/commons-codec-1.11.jar:/opt/openas2/bin/../lib/commons-io-2.16.1.jar:/opt/openas2/bin/../lib/commons-lang3-3.14.0.jar:/opt/openas2/bin/../lib/commons-logging-1.3.1.jar:/opt/openas2/bin/../lib/dom4j-2.1.4.jar:/opt/openas2/bin/../lib/grizzly-framework-4.0.2.jar:/opt/openas2/bin/../lib/grizzly-http-4.0.2.jar:/opt/openas2/bin/../lib/grizzly-http-server-4.0.2.jar:/opt/openas2/bin/../lib/h2-2.2.224.jar:/opt/openas2/bin/../lib/hk2-api-4.0.0-M1.jar:/opt/openas2/bin/../lib/hk2-locator-4.0.0-M1.jar:/opt/openas2/bin/../lib/hk2-utils-4.0.0-M1.jar:/opt/openas2/bin/../lib/httpclient-4.5.14.jar:/opt/openas2/bin/../lib/httpcore-4.4.16.jar:/opt/openas2/bin/../lib/jackson-annotations-2.17.1.jar:/opt/openas2/bin/../lib/jackson-core-2.17.1.jar:/opt/openas2/bin/../lib/jackson-databind-2.17.1.jar:/opt/openas2/bin/../lib/jackson-module-jakarta-xmlbind-annotations-2.16.1.jar:/opt/openas2/bin/../lib/jackson-module-jaxb-annotations-2.17.1.jar:/opt/openas2/bin/../lib/jakarta.activation-api-1.2.2.jar:/opt/openas2/bin/../lib/jakarta.annotation-api-3.0.0-M1.jar:/opt/openas2/bin/../lib/jakarta.inject-api-2.0.1.jar:/opt/openas2/bin/../lib/jakarta.validation-api-3.1.0-M1.jar:/opt/openas2/bin/../lib/jakarta.ws.rs-api-3.1.0.jar:/opt/openas2/bin/../lib/jakarta.xml.bind-api-2.3.3.jar:/opt/openas2/bin/../lib/javassist-3.29.2-GA.jar:/opt/openas2/bin/../lib/javax.activation-api-1.2.0.jar:/opt/openas2/bin/../lib/javax.annotation-api-1.3.2.jar:/opt/openas2/bin/../lib/javax.mail-1.6.2.jar:/opt/openas2/bin/../lib/javax.ws.rs-api-2.1.1.jar:/opt/openas2/bin/../lib/jaxb-api-2.4.0-b180830.0359.jar:/opt/openas2/bin/../lib/jaxb-core-4.0.5.jar:/opt/openas2/bin/../lib/jaxb-impl-4.0.5.jar:/opt/openas2/bin/../lib/jersey-client-4.0.0-M1.jar:/opt/openas2/bin/../lib/jersey-common-4.0.0-M1.jar:/opt/openas2/bin/../lib/jersey-container-grizzly2-http-4.0.0-M1.jar:/opt/openas2/bin/../lib/jersey-entity-filtering-4.0.0-M1.jar:/opt/openas2/bin/../lib/jersey-hk2-4.0.0-M1.jar:/opt/openas2/bin/../lib/jersey-media-json-jackson-4.0.0-M1.jar:/opt/openas2/bin/../lib/jersey-server-4.0.0-M1.jar:/opt/openas2/bin/../lib/openas2-server-3.10.1.jar:/opt/openas2/bin/../lib/osgi-resource-locator-1.0.3.jar:/opt/openas2/bin/../lib/sentry-7.8.0.jar:/opt/openas2/bin org.openas2.app.OpenAS2Server

2024-05-23 05:03:35.514 FINE OpenAS2Server: Retrieving config file...
2024-05-23 05:03:35.814 FINE OpenAS2Server: Using MANIFEST file:/opt/openas2/lib/openas2-server-3.10.1.jar!/META-INF/MANIFEST.MF
2024-05-23 05:03:35.850 FINE XMLSession: Loading configuration...
2024-05-23 05:03:35.850 FINE XMLSession: Loading properties...
Exception in thread "main" org.openas2.WrappedException: Error creating component: org.openas2.cert.PKCS12CertificateFactory
        at org.openas2.util.XMLUtil.getComponent(XMLUtil.java:74)
        at org.openas2.XMLSession.loadCertificates(XMLSession.java:224)
        at org.openas2.XMLSession.load(XMLSession.java:111)
        at org.openas2.XMLSession.<init>(XMLSession.java:77)
        at org.openas2.app.OpenAS2Server$Builder.run(OpenAS2Server.java:182)
        at org.openas2.app.OpenAS2Server.main(OpenAS2Server.java:72)
Caused by: org.openas2.WrappedException: java.io.IOException: error constructing MAC: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.openas2.cert.PKCS12CertificateFactory.load(PKCS12CertificateFactory.java:237)
        at org.openas2.cert.PKCS12CertificateFactory.load(PKCS12CertificateFactory.java:221)
        at org.openas2.cert.PKCS12CertificateFactory.load(PKCS12CertificateFactory.java:244)
        at org.openas2.cert.PKCS12CertificateFactory.init(PKCS12CertificateFactory.java:214)
        at org.openas2.util.XMLUtil.getComponent(XMLUtil.java:70)
        ... 5 more
Caused by: java.io.IOException: error constructing MAC: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
        at org.bouncycastle.jcajce.provider.keystore.util.AdaptingKeyStoreSpi.engineLoad(Unknown Source)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at org.openas2.cert.PKCS12CertificateFactory.load(PKCS12CertificateFactory.java:234)
        ... 9 more

**Comment by epositiveDevang** [comment]
After updating JDK to 18, it started.
Devang
