### ISSUE TITLE
Issue to send an encrypt message to Open AS2, i have got an error

### ISSUE THREAD

**Issue by TenorD1** [OpenAS2/OpenAs2App#396]
We have our solution to manage AS2 protocol, and use it successfully with other solutions like Mendelson.
We try to send an encrypted message to your AS2 serveur but something goes wrong, we obtained the following trace error

2024-10-22 15:20:39.006 FINE AS2MDNReceiverHandler: DISPOSITION MIC ALG: sha1   IMPORTANCE: required
2024-10-22 15:20:39.116 FINE MDNSenderModule: sent MDN [automatic-action/mdn-sent-automatically; processed/error:decryption-failed] [<46f3c176-a79b-440c-97d4-50cb5ef17918@a7a542eb-87d8-482b-809f-5b446b947118>]
2024-10-22 15:20:40.223 ERROR OpenAS2Exception: Error occurred:: Malformed content.
    Sources: {message=Message From:{as2_id=Tenor_GLN, name=PartnerA, email=tenor@partnera.com, x509_alias=as2_tenor_dex}To:{as2_id=OpenAS2_ID, name=MyCompany, email=as2msgs@openas2.com, x509_alias=mycompany}
Headers:{Content-Type=application/pkcs7-mime; smime-type=enveloped-data; name="smime.p7m", Host=10.69.0.54:10080, AS2-From=Tenor_GLN, AS2-To=OpenAS2_ID, AS2-Version=1.0, Message-Id=<46f3c176-a79b-440c-97d4-50cb5ef17918@a7a542eb-87d8-482b-809f-5b446b947118>, Mime-Version=1.0, From=Tenor AS2, Subject=AS2 Tenor TO OpenAS2, Content-Transfer-Encoding=base64, Disposition-Notification-To=DataExchanger_AS2Server@Tenor.fr, Disposition-Notification-Options=signed-receipt-protocol=required, pkcs7-signature; signed-receipt-micalg=required,sha1, Connection=Keep-Alive, Content-Disposition=null, Content-Length=3102252}
Attributes:{HTTP_REQUEST_TYPE=POST, destination_ip=/10.69.0.54, destination_port=10080, HTTP_REQUEST_URL=/, source_port=64133, source_ip=/10.69.0.50}
MDN:MDN From:{as2_id=OpenAS2_ID, name=MyCompany, email=as2msgs@openas2.com, x509_alias=mycompany}To:{as2_id=Tenor_GLN, name=PartnerA, email=tenor@partnera.com, x509_alias=as2_tenor_dex}
Headers:{Date=mar., 22 oct. 2024 15:20:39 +0200, From=as2msgs@openas2.com, Message-Id=<20241022152039+0200-218-Tenor_GLN_OpenAS2_ID_null>, Subject=Your Requested MDN Response re: AS2 Tenor TO OpenAS2, MIME-Version=1.0, Content-Type=multipart/signed; protocol="application/pkcs7-signature"; micalg=sha-1; 	boundary="----=_Part_3_1033916185.1729603239047", AS2-To=Tenor_GLN, AS2-From=OpenAS2_ID, AS2-Version=1.1, Connection=close, TE, User-Agent=OpenAS2 Server v3.11.0, Server=OpenAS2 Server v3.11.0, Content-Length=1987}
Attributes:{FINAL_RECIPIENT=rfc822; OpenAS2_ID, MIC=null, REPORTING_UA=OpenAS2 Server v3.11.0@/10.69.0.54:10080, ORIGINAL_MESSAGE_ID=<46f3c176-a79b-440c-97d4-50cb5ef17918@a7a542eb-87d8-482b-809f-5b446b947118>, ORIGINAL_RECIPIENT=rfc822; OpenAS2_ID, DISPOSITION=automatic-action/MDN-sent-automatically; processed/Error:decryption-failed}
Text: 
The message sent to Recipient OpenAS2_ID on null with Subject AS2 Tenor TO OpenAS2 has been received, but an error occured decrypting the content.
}
org.openas2.DispositionException: automatic-action/MDN-sent-automatically; processed/Error:decryption-failed
	at org.openas2.processor.receiver.AS2ReceiverHandler.decryptAndVerify(AS2ReceiverHandler.java:363)
	at org.openas2.processor.receiver.AS2ReceiverHandler.handle(AS2ReceiverHandler.java:210)
	at org.openas2.processor.receiver.NetModule$ConnectionHandler.run(NetModule.java:176)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: org.bouncycastle.cms.CMSException: Malformed content.
	at org.bouncycastle.cms.CMSUtils.readContentInfo(Unknown Source)
	at org.bouncycastle.cms.CMSUtils.readContentInfo(Unknown Source)
	at org.bouncycastle.cms.CMSEnvelopedData.<init>(Unknown Source)
	at org.bouncycastle.mail.smime.SMIMEEnveloped.<init>(Unknown Source)
	at org.openas2.lib.helper.BCCryptoHelper.decrypt(BCCryptoHelper.java:211)
	at org.openas2.processor.receiver.AS2ReceiverHandler.decryptAndVerify(AS2ReceiverHandler.java:338)
	... 5 more
Caused by: java.lang.IllegalArgumentException: unknown object in getInstance: org.bouncycastle.asn1.DLTaggedObject
	at org.bouncycastle.asn1.ASN1Sequence.getInstance(Unknown Source)
	at org.bouncycastle.asn1.cms.ContentInfo.getInstance(Unknown Source)
	... 11 more
2024-10-22 15:20:41.355 ERROR OpenAS2Exception: Error occurred:: Stored invalid message to E:\OpenAS2\config\..\data\inbox\error\20241022032040.0c9f57bb-73da-44d7-8027-14ba55989646
    Sources: {}
org.openas2.message.InvalidMessageException: Stored invalid message to E:\OpenAS2\config\..\data\inbox\error\20241022032040.0c9f57bb-73da-44d7-8027-14ba55989646
	at org.openas2.processor.receiver.NetModule.handleError(NetModule.java:142)
	at org.openas2.processor.receiver.AS2ReceiverHandler.handle(AS2ReceiverHandler.java:281)
	at org.openas2.processor.receiver.NetModule$ConnectionHandler.run(NetModule.java:176)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
2024-10-22 15:30:44.530 FINE AS2ReceiverHandler: received 3102252 bytes in 0.17 seconds at 174.32 MBps 10.69.0.50 49506 [<c48d45a2-034c-4cfb-a3c6-b2fe5afc4b2b@39ac69ae-8420-41fe-ba2d-1fe3a1aa8b12>]
2024-10-22 15:30:46.465 ERROR AS2ReceiverHandler: Error extracting received message: java.lang.IllegalArgumentException: unknown object in getInstance: org.bouncycastle.asn1.DLTaggedObject [<c48d45a2-034c-4cfb-a3c6-b2fe5afc4b2b@39ac69ae-8420-41fe-ba2d-1fe3a1aa8b12>]
org.bouncycastle.cms.CMSException: Malformed content.
	at org.bouncycastle.cms.CMSUtils.readContentInfo(Unknown Source)
	at org.bouncycastle.cms.CMSUtils.readContentInfo(Unknown Source)
	at org.bouncycastle.cms.CMSEnvelopedData.<init>(Unknown Source)
	at org.bouncycastle.mail.smime.SMIMEEnveloped.<init>(Unknown Source)
	at org.openas2.lib.helper.BCCryptoHelper.decrypt(BCCryptoHelper.java:211)
	at org.openas2.processor.receiver.AS2ReceiverHandler.decryptAndVerify(AS2ReceiverHandler.java:338)
	at org.openas2.processor.receiver.AS2ReceiverHandler.handle(AS2ReceiverHandler.java:210)
	at org.openas2.processor.receiver.NetModule$ConnectionHandler.run(NetModule.java:176)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.IllegalArgumentException: unknown object in getInstance: org.bouncycastle.asn1.DLTaggedObject
	at org.bouncycastle.asn1.ASN1Sequence.getInstance(Unknown Source)
	at org.bouncycastle.asn1.cms.ContentInfo.getInstance(Unknown Source)
	... 11 more
	
	We have done some try but unable to have any clue about the problem, the message error is very cryptic for an external user could you give some help to know what going wrong, i paste the complete request that we have sent to your AS2 server.
	
We are in .net plateform, any issue with Java ?
[request.txt](https://github.com/user-attachments/files/17477366/request.txt)

**Comment by uhurusurfa** [comment]
It could be that the partner using OpenAS2 has not set it up correctly ... possibly their private key is somehow corrupted when they imported their public and private key.
Ask your partner to provide the version of OpenAS2 they are currently running and confirm if they are successfully communicating with other partners.

**Comment by uhurusurfa** [comment]
Closing due to lack of feedback
