### ISSUE TITLE
Last PR broke docker build for WebUI

### ISSUE THREAD

**Issue by yberezkin** [OpenAS2/OpenAs2App#400]
> `docker build -t openas2_webui:latest -f Dockerfile_WebUI . --no-cache --progress=plain`

```
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile_WebUI
#1 transferring dockerfile: 413B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/nginx:stable-alpine
#2 DONE 0.1s

#3 [internal] load metadata for docker.io/library/node:16-alpine
#3 DONE 0.1s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [web-builder 1/7] FROM docker.io/library/node:16-alpine@sha256:a1f9d027912b58a7c75be7716c97cfbc6d3099f3a97ed84aa490be9dee20e787
#5 CACHED

#6 [stage-1 1/2] FROM docker.io/library/nginx:stable-alpine@sha256:5b44a5ab8ab467854f2bf7b835a32f850f32eb414b749fbf7ed506b139cd8d6b
#6 CACHED

#7 [internal] load build context
#7 transferring context: 2.18kB done
#7 DONE 0.0s

#8 [web-builder 2/7] RUN npm install -g --force yarn
#8 0.517 npm WARN using --force Recommended protections disabled.
#8 1.323 
#8 1.323 added 1 package, and audited 2 packages in 831ms
#8 1.324 
#8 1.324 found 0 vulnerabilities
#8 1.324 npm notice 
#8 1.325 npm notice New major version of npm available! 8.19.4 -> 10.9.0
#8 1.325 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.9.0>
#8 1.325 npm notice Run `npm install -g npm@10.9.0` to update!
#8 1.325 npm notice 
#8 DONE 1.4s

#9 [web-builder 3/7] COPY ./WebUI /usr/src/webui
#9 DONE 0.0s

#10 [web-builder 4/7] WORKDIR /usr/src/webui
#10 DONE 0.0s

#11 [web-builder 5/7] RUN yarn install
#11 0.401 yarn install v1.22.22
#11 0.494 [1/4] Resolving packages...
#11 0.975 [2/4] Fetching packages...
#11 12.12 warning url-loader@1.1.2: Invalid bin field for "url-loader".
#11 18.37 [3/4] Linking dependencies...
#11 18.37 warning " > bootstrap@5.3.3" has unmet peer dependency "@popperjs/core@^2.11.8".
#11 18.37 warning "bootstrap-vue > bootstrap@4.6.2" has unmet peer dependency "jquery@1.9.1 - 3".
#11 18.37 warning "bootstrap-vue > portal-vue@2.1.7" has incorrect peer dependency "vue@^2.5.18".
#11 18.37 warning " > vue-time-date-range-picker@1.6.0" has incorrect peer dependency "vue@^2.6.11".
#11 18.37 warning " > vuex@3.6.2" has incorrect peer dependency "vue@^2.0.0".
#11 18.37 warning " > @babel/eslint-parser@7.25.1" has unmet peer dependency "@babel/core@^7.11.0".
#11 18.37 warning " > @babel/eslint-parser@7.25.1" has incorrect peer dependency "eslint@^7.5.0 || ^8.0.0 || ^9.0.0".
#11 18.38 warning " > sass-loader@10.5.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
#11 24.52 [4/4] Building fresh packages...
#11 26.01 Done in 25.61s.
#11 DONE 26.8s

#12 [web-builder 6/7] RUN npx browserslist@latest --update-db
#12 2.125 npm WARN exec The following package was not found and will be installed: browserslist@4.24.2
#12 2.775 The --update-db command is deprecated.
#12 2.775 Please use npx update-browserslist-db@latest instead.
#12 2.775 Browserslist DB update will still be made.
#12 3.294 Latest version:     1.0.30001674
#12 3.303 Installed version:  1.0.30001651
#12 3.303 Removing old caniuse-lite from lock file
#12 3.306 Installing new caniuse-lite version
#12 3.306 $ yarn add -W caniuse-lite
#12 9.006 warning " > bootstrap@5.3.3" has unmet peer dependency "@popperjs/core@^2.11.8".
#12 9.006 warning "bootstrap-vue > bootstrap@4.6.2" has unmet peer dependency "jquery@1.9.1 - 3".
#12 9.006 warning "bootstrap-vue > portal-vue@2.1.7" has incorrect peer dependency "vue@^2.5.18".
#12 9.006 warning " > vue-time-date-range-picker@1.6.0" has incorrect peer dependency "vue@^2.6.11".
#12 9.006 warning " > vuex@3.6.2" has incorrect peer dependency "vue@^2.0.0".
#12 9.006 warning " > @babel/eslint-parser@7.25.1" has unmet peer dependency "@babel/core@^7.11.0".
#12 9.006 warning " > @babel/eslint-parser@7.25.1" has incorrect peer dependency "eslint@^7.5.0 || ^8.0.0 || ^9.0.0".
#12 9.006 warning " > sass-loader@10.5.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
#12 9.006 Cleaning package.json dependencies from caniuse-lite
#12 9.006 $ yarn remove -W caniuse-lite
#12 14.46 warning " > bootstrap@5.3.3" has unmet peer dependency "@popperjs/core@^2.11.8".
#12 14.46 warning "bootstrap-vue > bootstrap@4.6.2" has unmet peer dependency "jquery@1.9.1 - 3".
#12 14.46 warning "bootstrap-vue > portal-vue@2.1.7" has incorrect peer dependency "vue@^2.5.18".
#12 14.46 warning " > vue-time-date-range-picker@1.6.0" has incorrect peer dependency "vue@^2.6.11".
#12 14.46 warning " > vuex@3.6.2" has incorrect peer dependency "vue@^2.0.0".
#12 14.46 warning " > @babel/eslint-parser@7.25.1" has unmet peer dependency "@babel/core@^7.11.0".
#12 14.46 warning " > @babel/eslint-parser@7.25.1" has incorrect peer dependency "eslint@^7.5.0 || ^8.0.0 || ^9.0.0".
#12 14.46 warning " > sass-loader@10.5.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
#12 14.46 caniuse-lite has been successfully updated
#12 14.46 
#12 14.46 No target browser changes
#12 DONE 14.7s

#13 [web-builder 7/7] RUN yarn run build
#13 0.274 yarn run v1.22.22
#13 0.310 $ vue-cli-service build
#13 0.898 
#13 0.899 -  Building for production...
#13 1.683  ERROR  Error: 
#13 1.683        
#13 1.683 Vue packages version mismatch:
#13 1.683        
#13 1.683 - vue@3.0.0 (/usr/src/webui/node_modules/vue/index.js)
#13 1.683 - vue-template-compiler@2.7.16 (/usr/src/webui/node_modules/vue-template-compiler/package.json)
#13 1.683        
#13 1.683 This may cause things to work incorrectly. Make sure to use the same version for both.
#13 1.683 If you are using vue-loader@>=10.0, simply update vue-template-compiler.
#13 1.683 If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
#13 1.683        
#13 1.684 Error: 
#13 1.684 
#13 1.684 Vue packages version mismatch:
#13 1.684 
#13 1.684 - vue@3.0.0 (/usr/src/webui/node_modules/vue/index.js)
#13 1.684 - vue-template-compiler@2.7.16 (/usr/src/webui/node_modules/vue-template-compiler/package.json)
#13 1.684 
#13 1.684 This may cause things to work incorrectly. Make sure to use the same version for both.
#13 1.684 If you are using vue-loader@>=10.0, simply update vue-template-compiler.
#13 1.684 If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
#13 1.684 
#13 1.684     at Object.<anonymous> (/usr/src/webui/node_modules/vue-template-compiler/index.js:10:9)
#13 1.684     at Module._compile (node:internal/modules/cjs/loader:1198:14)
#13 1.684     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
#13 1.684     at Module.load (node:internal/modules/cjs/loader:1076:32)
#13 1.684     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
#13 1.684     at Module.require (node:internal/modules/cjs/loader:1100:19)
#13 1.684     at require (node:internal/modules/cjs/helpers:119:18)
#13 1.684     at loadFromContext (/usr/src/webui/node_modules/vue-loader/lib/compiler.js:30:10)
#13 1.684     at loadTemplateCompiler (/usr/src/webui/node_modules/vue-loader/lib/compiler.js:37:12)
#13 1.684     at exports.resolveCompiler (/usr/src/webui/node_modules/vue-loader/lib/compiler.js:25:23)
#13 1.684     at VueLoaderPlugin.apply (/usr/src/webui/node_modules/vue-loader/lib/plugin-webpack4.js:91:22)
#13 1.684     at VueLoaderPlugin.apply (/usr/src/webui/node_modules/vue-loader/lib/plugin.js:13:16)
#13 1.684     at webpack (/usr/src/webui/node_modules/webpack/lib/webpack.js:51:13)
#13 1.684     at /usr/src/webui/node_modules/@vue/cli-service/lib/commands/build/index.js:192:5
#13 1.684     at new Promise (<anonymous>)
#13 1.684     at build (/usr/src/webui/node_modules/@vue/cli-service/lib/commands/build/index.js:191:10)
#13 1.714 error Command failed with exit code 1.
#13 1.714 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#13 ERROR: process "/bin/sh -c yarn run build" did not complete successfully: exit code: 1
------
 > [web-builder 7/7] RUN yarn run build:
1.684     at loadTemplateCompiler (/usr/src/webui/node_modules/vue-loader/lib/compiler.js:37:12)
1.684     at exports.resolveCompiler (/usr/src/webui/node_modules/vue-loader/lib/compiler.js:25:23)
1.684     at VueLoaderPlugin.apply (/usr/src/webui/node_modules/vue-loader/lib/plugin-webpack4.js:91:22)
1.684     at VueLoaderPlugin.apply (/usr/src/webui/node_modules/vue-loader/lib/plugin.js:13:16)
1.684     at webpack (/usr/src/webui/node_modules/webpack/lib/webpack.js:51:13)
1.684     at /usr/src/webui/node_modules/@vue/cli-service/lib/commands/build/index.js:192:5
1.684     at new Promise (<anonymous>)
1.684     at build (/usr/src/webui/node_modules/@vue/cli-service/lib/commands/build/index.js:191:10)
1.714 error Command failed with exit code 1.
1.714 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
Dockerfile_WebUI:9
--------------------
   7 |     ARG VUE_APP_API_URL
   8 |     ENV VUE_APP_API_URL=${VUE_APP_API_URL:-http://localhost:8080}
   9 | >>> RUN yarn run build
  10 |     
  11 |     FROM nginx:stable-alpine
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn run build" did not complete successfully: exit code: 1
```

**Comment by uhurusurfa** [comment]
If you can figure out the correct versions for the lock file that works and raise a PR I will merge it.
Otherwise I will try to find some time to figure it out over the next few weeks unless someone else sorts it out in the interim.

**Comment by yberezkin** [comment]
> If you can figure out the correct versions for the lock file that works and raise a PR I will merge it. Otherwise I will try to find some time to figure it out over the next few weeks unless someone else sorts it out in the interim.

Do you have contribution instructions? Or standard `fork => push => open PR` 
Thanks :)

**Comment by uhurusurfa** [comment]
Sorry - read this and meant to answer when I had a chance but then forgot.
If you want to make contributions regularly then I can make you a member of the OpenAS2 team so you can create brnches within this repo and it makes the process much more simpole.
There are no specific instructions in terms of contributing but generally if you contriburte new code then unit tests are required.
In this case just getting the docker build running does not newed a unit test.

Whether you are a member or iuse the fork option, please eraise a PR against the master branch.
