### ISSUE TITLE
Error for MDN reception

### ISSUE THREAD

**Issue by blackillzone** [OpenAS2/OpenAs2App#60]
Hi,

Currently, we have an error with a partner (solved for the moment, by removing some configuration on their side), and I would like to know why. Here are the stack trace provided by OpenAS2:

```
org.openas2.DispositionException: automatic-action/MDN-sent-automatically; processed/Error:unexpected-processing-error
	at org.openas2.processor.receiver.AS2ReceiverHandler.decryptAndVerify(Unknown Source)
	at org.openas2.processor.receiver.AS2ReceiverHandler.handle(Unknown Source)
	at org.openas2.processor.receiver.NetModule$ConnectionThread.run(Unknown Source)
Caused by: java.security.NoSuchAlgorithmException: Unsupported or invalid algorithm: pkcs7-signature
	at org.openas2.lib.helper.BCCryptoHelper.convertAlgorithm(Unknown Source)
	at org.openas2.lib.helper.BCCryptoHelper.calculateMIC(Unknown Source)
	... 3 more
```

```
org.openas2.WrappedException: Error sending MDN
	at org.openas2.processor.receiver.AS2ReceiverHandler.processMDN(Unknown Source)
	at org.openas2.processor.receiver.AS2ReceiverHandler.handle(Unknown Source)
	at org.openas2.processor.receiver.NetModule$ConnectionThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Unknown signature type requested: PKCS7-SIGNATUREWITHRSA
	at org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder.generate(Unknown Source)
	at org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder.find(Unknown Source)
	at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.<init>(Unknown Source)
	at org.bouncycastle.cms.jcajce.JcaSimpleSignerInfoGeneratorBuilder$NamedHelper.createContentSigner(Unknown Source)
	at org.bouncycastle.cms.jcajce.JcaSimpleSignerInfoGeneratorBuilder.build(Unknown Source)
	at org.openas2.lib.helper.BCCryptoHelper.sign(Unknown Source)
	at org.openas2.util.AS2Util.createMDNData(Unknown Source)
	at org.openas2.util.AS2Util.createMDN(Unknown Source)
	... 3 more
```

Does this means they're using an unsupported signature ? Do you know if this will be implemented in some future releases ?
For information, we're running OpenAS2 in version 2.0.0, so maybe this is already supported, and we just need to upgrade, but I didn't find anything related to this signature type.

Thanks for the time.

**Comment by uhurusurfa** [comment]
I will look into this in the next few days as I am on holiday at the moment

**Comment by uhurusurfa** [comment]
Did you solve this yet?

The algorithm is definitely one I have never heard of nor can identify as a valid algorithm.

the supported algorithms are found in this web page https://bouncycastle.org/specifications.html 
 ... search for "Signature Algorithms" in that web pge and you will see the list.

My guess is that your partner was guessing and misconfigured their algorithm name.

**Comment by rde-infologic** [comment]
I have same issue but we can resolve it, the "Disposition-Notification-Options:" header must be in the followin order : signed-receipt-protocol then signed-receipt-micalg for OpenAS2

If your partner sent you then follwing Disposition-Notification-Options header, 

> Disposition-Notification-Options: signed-receipt-micalg=required, sha256; signed-receipt-protocol=required, pkcs7-signature

You will get the same error.

For me as the TODO comment said this parse method is too rigid and doesn't check parameters (signed-receipt-protocol, signed-receipt-micalg) orders and optional values correctly.

![image](https://github.com/user-attachments/assets/f242dec7-c5be-44c1-aa12-9879e71c88c4)

Regards,

**Comment by uhurusurfa** [comment]
An enhanced parser will be included in the next release ensuring order of dispoistion parameters is not important
