### ISSUE TITLE
How to use Health Check Module?

### ISSUE THREAD

**Issue by tsneed290** [OpenAS2/OpenAs2App#81]
Trying out this project for a potential solution. Was wondering how exactly to interact with the HealthModule? I have started a barebones server and am making an HTTP GET request to http://localhost:10099. 

I'm seeing errors in the logs as such:

```
java.io.IOException: Invalid HTTP Request: Token Count - 0::: String length - 0 ::: String -
	at org.openas2.util.HTTPUtil.readRequest(HTTPUtil.java:413)
	at org.openas2.util.HTTPUtil.readHTTP(HTTPUtil.java:270)
	at org.openas2.processor.receiver.HealthCheckHandler.handle(HealthCheckHandler.java:44)
	at org.openas2.processor.receiver.NetModule$ConnectionThread.run(NetModule.java:201)
```

So I feel like I'm missing something. Couldn't find anything in the How To document on what type of request to construct. Any pointers would be appreciated!

**Comment by uhurusurfa** [comment]
Please can you raise application use issues here: https://sourceforge.net/p/openas2/discussion/
